import { ChangeDetectionStrategy, Component } from '@angular/core';
import { FormControl } from '@angular/forms';

@Component({
  selector: 'matmulti-search-select',
  templateUrl: './multimatselect.component.html',
  styleUrls: ['./multimatselect.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MultimatselectComponent {
  toppings = new FormControl('');
  toppingList: string[] = [
    'Extra cheese',
    'Mushroom',
    'Onion',
    'Pepperoni',
    'Sausage',
    'Tomato',
    'Green pepper',
    'Black olives',
    'Ham',
    'Pineapple',
    'Bacon',
    'Jalapeno',
    'Spinach',
    'Chicken',
    'Anchovies',
    'Artichokes',
    'Basil',
    'Broccoli',
    'Capers',
    'Cheddar cheese',
    'Feta cheese',
    'Garlic',
    'Goat cheese',
    'Lettuce',
    'Parmesan cheese',
    'Red onion',
    'Ricotta cheese',
    'Sun-dried tomatoes',
    'Sweet corn',
    'Mozzarella cheese',
    'Provolone cheese',
    'Roasted red peppers',
    'Salami',
    'Cherry tomatoes',
    'Chopped onions',
    'Cilantro',
    'Cucumber',
    'Grilled chicken',
    'Green olives',
    'Ground beef',
    'Italian sausage',
    'Kalamata olives',
    'Meatballs',
    'Oregano',
    'Pesto',
    'Roma tomatoes',
    'Scallions',
    'Shrimp',
    'Sliced almonds',
    'Sliced ham',
    'Sliced turkey',
    'Smoked salmon',
    'Sundried tomatoes',
    'Swiss cheese',
    'Thyme',
    'Tuna',
    'Turkey sausage',
    'Yellow peppers',
    'Zucchini',
    'Brie cheese',
    'Blue cheese',
    'Chives',
    'Cajun seasoning',
    'Chorizo',
    'Cottage cheese',
    'Crumbled bacon',
    'Fontina cheese',
    'Goat cheese',
    'Gouda cheese',
    'Havarti cheese',
    'Monterey Jack cheese',
    'Muenster cheese',
    'Paprika',
    'Pecorino cheese',
    'Pepper jack cheese',
    'Pickles',
    'Pine nuts',
    'Pimento',
    'Pinto beans',
    'Raisins',
    'Red bell pepper',
    'Red cabbage',
    'Red pepper flakes',
    'Sesame seeds',
    'Sliced beef',
    'Sliced pork',
    'Sour cream',
    'Tarragon',
    'Tofu',
    'Tofurkey',
    'Truffle oil',
    'Walnuts',
    'White cheddar cheese',
    'Yellow bell pepper',
  ];
}
